-- MySQL Script generated by MySQL Workbench
-- Mon May 30 11:25:32 2016
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Music
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `information` ;

-- -----------------------------------------------------
-- Schema Music
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `information` DEFAULT CHARACTER SET utf8 ;
USE `information` ;



-- -----------------------------------------------------
-- Table `information`.`dbworkstables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information`.`sys_tables`;

CREATE TABLE IF NOT EXISTS `information`.`sys_tables` (
 `sys_tablesId` INT NOT NULL AUTO_INCREMENT,
 `tablename` VARCHAR(100) NOT NULL,
 `comments` VARCHAR(5000),
 PRIMARY KEY (`tableId`));

-- -----------------------------------------------------
-- Table `information`.`dbworkstables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information`.`sys_fields`;

CREATE TABLE IF NOT EXISTS `information`.`sys_fields` (
 `sys_fieldsId` INT NOT NULL AUTO_INCREMENT,
 `tableId` INT NOT NULL,
 `valfield` VARCHAR(100) NOT NULL,
 `valtype` VARCHAR(100) NOT NULL,
 `valnull` VARCHAR(10) NOT NULL,
 `valkey` VARCHAR(10),
 `valdefault` VARCHAR(500),
 `valextra` VARCHAR(500),
 PRIMARY KEY (`tablefieldId`));


 -- -----------------------------------------------------
-- Table `information`.`dbworkstables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `information`.`sys_docs`;

CREATE TABLE IF NOT EXISTS `information`.`sys_docs` (
 `sys_docsId` INT NOT NULL AUTO_INCREMENT,
 `Title` VARCHAR(100) NOT NULL,
 `TypeOfDoc` VARCHAR(100),
 `Document` BLOB,
 PRIMARY KEY (`tableId`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
